# Generated by Django 5.2.8 on 2025-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('closings', models.CharField(default=None, max_length=100)),
                ('delays', models.CharField(default=None, max_length=100)),
                ('dismissals', models.CharField(default=None, max_length=100)),
                ('non_traditional', models.CharField(default=None, max_length=100)),
                ('bus_info', models.CharField(default=None, max_length=100)),
                ('last_update', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
    ]
