# Generated by Django 5.2.8 on 2025-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='delay_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
