# Generated by Django 5.2.8 on 2025-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0002_county_delay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='specific_school_closings',
            field=models.TextField(blank=True, default=''),
        ),
    ]
