# Generated by Django 5.2.8 on 2025-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0003_county_specific_school_closings'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='specific_school_dismissals',
            field=models.TextField(blank=True, default=''),
        ),
    ]
