# Generated by Django 5.2.8 on 2025-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0004_county_specific_school_dismissals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='bus_info',
        ),
        migrations.AddField(
            model_name='county',
            name='specific_school_delays',
            field=models.TextField(blank=True, default=''),
        ),
    ]
